Implement objects
novalain/gi-ray pull request #46
Opened 2016-09-16 19:59 UTC by novalain

Restructured classes and Scene. Only implemented Tetrahedron so far, creating Sphere as separate issue

2016-09-16 23:26 UTC, Carlbaum commented on src/main.cc
> +#include "triangle.h"
@ row #8: 2nd include of triangle.h

2016-09-16 23:28 UTC, Carlbaum requested changes
Remove row #8 from main.cc: 
triangle.h included twice

2016-09-16 23:56 UTC, Carlbaum commented on include/tetrahedron.h
> +  public:
No indents on public, private nor protected in .h files

2016-09-16 23:56 UTC, Carlbaum commented on include/tetrahedron.h
> +  public:
@ row #8

2016-09-16 23:57 UTC, Carlbaum commented on include/triangle_based_object.h
> +  protected:
@ row #9 no indent

2016-09-17 00:06 UTC, novalain commented on include/triangle_based_object.h
> +  protected:
Already fixed in later commit 😌  
![skarmavbild 2016-09-17 kl 02 05 47](https://cloud.githubusercontent.com/assets/7224052/18604300/4c618b1e-7c7b-11e6-8821-5bdd5fd5601c.png)

2016-09-17 00:08 UTC, novalain commented on include/tetrahedron.h
> +  public:
also fixed already

2016-09-17 00:18 UTC, Carlbaum commented on include/triangle.h
> +  bool RayIntersection(Ray& ray);
Wasn't this changed to return a float.. not a bool?

2016-09-17 00:21 UTC, Carlbaum approved these changes

2016-09-17 09:01 UTC, novalain commented on include/triangle.h
> +  bool RayIntersection(Ray& ray);
Yes but in the other PR. will rebase and resolve conflicts :sleepy:

2016-09-18 12:41 UTC, closed without merging